#!/bin/bash
# Script para autenticar com GitHub usando Token Pessoal (PAT)

echo "🔐 Autenticação GitHub com Token Pessoal"
echo "=========================================="
echo ""
echo "Opção 1: HTTPS com Token (Recomendado)"
echo "------"
echo "1. Abra um terminal em /home/linux_daniel/copiloto.v3/project"
echo "2. Execute:"
echo ""
echo "   git push -u origin V4_12_09_25"
echo ""
echo "3. Quando pedir 'Username for https://github.com':"
echo "   - Digite: danielbgcarneiro"
echo ""
echo "4. Quando pedir 'Password for https://...':"
echo "   - Cole seu Personal Access Token (PAT) do GitHub"
echo "   - Não use sua senha, use o token!"
echo ""
echo ""
echo "Opção 2: Armazenar credenciais (para futuras operações)"
echo "------"
echo "Execute:"
echo ""
echo "   git config --global credential.helper store"
echo ""
echo "Depois faça push normalmente e as credenciais serão salvas em:"
echo "   ~/.git-credentials"
echo ""
echo ""
echo "Opção 3: SSH (Alternativa mais segura)"
echo "------"
echo "1. Gere chave SSH:"
echo "   ssh-keygen -t ed25519 -C 'seu@email.com'"
echo ""
echo "2. Adicione a chave pública ao GitHub:"
echo "   - Configurações → SSH and GPG keys → Nova chave SSH"
echo ""
echo "3. Altere remoto para SSH:"
echo "   git remote set-url origin git@github.com:danielbgcarneiro/copiloto_focco.git"
echo ""
echo "4. Depois faça push sem precisar autenticar novamente"
echo ""
echo ""
echo "📍 Status atual do repositório:"
git status
echo ""
echo "🔗 Remoto configurado:"
git remote -v
echo ""
echo "💾 Branch local:"
git branch
echo ""
echo "📊 Commits pendentes:"
git log origin/V4_12_09_25..V4_12_09_25 --oneline 2>/dev/null || echo "   Nenhum commit para comparar"
